### ISSUE TITLE
Idea: usage of Rustls

### ISSUE THREAD

**Issue by aellwein** [untoldwind/oauth-proxy-rs#1]
Instead of using vendored openssl lib, could it be possible to use rustls (maybe as optional feature)?

**Comment by aellwein** [comment]
This would also make the build truly cross-platform (for now, the Cargo.toml references musl libs).

**Comment by untoldwind** [comment]
Unluckily "openssl-sys" is a transient dependency of the "reqwest" crate. Even with default-features disabled it is still required during compilation.
It should not be used in the release code.

**Comment by aellwein** [comment]
Thanks!
