### ISSUE TITLE
Idea: OAuth proxy as a library

### ISSUE THREAD

**Issue by aellwein** [untoldwind/oauth-proxy-rs#2]
Hello!
Deployment of many small servers/services, each with its own OAuth proxy can be quite tedious (i'm thinking about 
static self-contained websites served in container, but protected with OAuth).

A nice feature would be if oauth-proxy-rs could be embedded as a library inside some service. I could imagine a library call with (maybe already created socket?) parameters passed to it and also the backend address/url (maybe even listening on localhost address to not expose it to the public). 

WDYT?

**Comment by untoldwind** [comment]
Primarily the proxy was intended to run as a sidecar in a kubernetes environment (i.e. as additional container inside a pod).

I am no sure if converting it to a library would make much sense. All the "heavy duty" is already handled by the "openid" crate.

Also: What languages/frameworks should be supported? The benefit of an extra process is that the webservice itself can be written in any language/framework

**Comment by aellwein** [comment]
Ok, i see. For my use case (self-contained web server in Rust with embedded static pages, but protected with OAuth) it's probably better to instrument the "openid" crate directly, because i want to spare the separate container/process.
Closing the issue.
